# SQLAlchemy-compatible schema for 'sales' table
SALES_SQLALCHEMY_SCHEMA = {
    "__tablename__": "sales",
    "columns": [
        {
            "name": "sale_id",
            "type": "Integer",
            "primary_key": True,
            "autoincrement": True,
            "encrypt": False,
            "required": False,
        },
        {
            "name": "transaction_id",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "customer_id",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "product_id",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "store_id",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "quantity",
            "type": "Integer",
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "unit_price",
            "type": "Numeric",
            "precision": 10,
            "scale": 2,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "discount",
            "type": "Numeric",
            "precision": 4,
            "scale": 2,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "total_amount",
            "type": "Numeric",
            "precision": 12,
            "scale": 2,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "payment_method",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "sale_date",
            "type": "Date",
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "sale_time",
            "type": "Time",
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "created_at",
            "type": "DateTime",
            "nullable": True,
            "encrypt": False,
            "required": False,
        },
    ],
}

# SQLAlchemy-compatible schema for 'suppliers' table
SUPPLIERS_SQLALCHEMY_SCHEMA = {
    "__tablename__": "suppliers",
    "columns": [
        {
            "name": "supplier_id",
            "type": "String",
            "length": 50,
            "primary_key": True,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "name",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "country",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "contact_email",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
    ],
}

# SQLAlchemy-compatible schema for 'products' table
PRODUCTS_SQLALCHEMY_SCHEMA = {
    "__tablename__": "products",
    "columns": [
        {
            "name": "product_id",
            "type": "String",
            "length": 50,
            "primary_key": True,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "name",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "category",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "current_price",
            "type": "Numeric",
            "precision": 10,
            "scale": 2,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "cost",
            "type": "Numeric",
            "precision": 10,
            "scale": 2,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "supplier_id",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "stock",
            "type": "Integer",
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
    ],
}

# SQLAlchemy-compatible schema for 'customers' table
CUSTOMERS_SQLALCHEMY_SCHEMA = {
    "__tablename__": "customers",
    "columns": [
        {
            "name": "customer_id",
            "type": "String",
            "length": 50,
            "primary_key": True,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "first_name",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "last_name",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "email",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "phone",
            "type": "String",
            "length": 20,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "join_date",
            "type": "Date",
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "country",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "city",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
    ],
}

# SQLAlchemy-compatible schema for 'stores' table
STORES_SQLALCHEMY_SCHEMA = {
    "__tablename__": "stores",
    "columns": [
        {
            "name": "store_id",
            "type": "String",
            "length": 50,
            "primary_key": True,
            "encrypt": True,
            "required": True,
        },
        {
            "name": "name",
            "type": "String",
            "length": 100,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "city",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
        {
            "name": "country",
            "type": "String",
            "length": 50,
            "nullable": False,
            "encrypt": False,
            "required": True,
        },
    ],
}
